name: Update Favorite Tests List

on:
  schedule:
    - cron: "0 5 */30 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 supabase

      - name: Run script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL_2 }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY_2 }}
        run: |
          python favoriteTestCreator.py

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add favTests.html

          git diff --cached --quiet || git commit -m "Auto-update favorite tests list"
          git push
